blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',views.all_blogs,name='all_blogs'),
    path('<int:blog_id>', views.blog_detail, name='blog_detail'),

]

cv/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from project import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = 'index'),
    path('project/<int:project_id>', views.detail, name = 'detail'),
    path('blog/',include('blog.urls')),

]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    date = models.DateField()


    def __str__(self):
        return self.title
        
    # generate urls for particular blog details
    def get_absolute_url(self):
        return reverse('blog:blog_detail',kwargs={
            'blog_id':self.id
            })
    

project/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=300)
    image = models.ImageField(upload_to = 'cv/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

    # generate urls for particular project details
    def get_absolute_url(self):
        return reverse('detail',kwargs={
            'project_id': self.id
        })

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

# Create your views here.
def all_blogs(request):
    blogs = Blog.objects.order_by('-date')

    context ={
        'blogs': blogs,
    }

    return render(request,'blog/all_blogs.html',context)


def blog_detail(request, blog_id):
    blog = get_object_or_404(Blog,id=blog_id)
    context = {
        'blog':blog
    }
    return render(request,'blog/blog_detail.html',context)

project/views.py
from django.shortcuts import render, get_object_or_404
from .models import Project

# Create your views here.
def index(request):
    projects = Project.objects.all()    #showing projects from models to views
    context = {
        'projects': projects,
    }
    return render(request,'project/index.html',context)
    
# project's detail page    
def detail(request,project_id):
    project = get_object_or_404(Project,id=project_id)
    context = {
        'project': project,
    }
    return render(request,'project/detail.html',context)

blog/templates/blog/all_blogs.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Resume</title>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet"
        type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>

<body id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">
            <span class="d-block d-lg-none">Ajit Singh Kushwaha</span>
            <span class="d-none d-lg-block"><img class="img-fluid img-profile rounded-circle mx-auto mb-2"
                    src="{% static 'assets/img/profile_pic2.jpg' %}" alt="" /></span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'index' %}">Home</a></li>
                
            </ul>
        </div>
    </nav>
    <!-- Blog -->
    <section class="resume-section" id="projects">
        <div class="resume-section-content">
            <h2 class="mb-5">Blog Posts</h2>
            <div class="row">
                {% for blog in blogs %}
                <a href="{{ blog.get_absolute_url }}">
                    <div class="card" style="width: 18rem; margin: .1em;">

                        {% if blog.image %}
                        <img class="card-img-top" src="{{ blog.image.url }}" alt="blog image cap">
                        {% endif %}
                        <div class="card-body">
                            <h4 class="card-title">{{ blog.title }}</h4>
                </a>
                <p class="card-text">{{ blog.description|truncatechars:60 }}</p><br>
                <p style="float: right">{{ blog.date}}</p>
                <!--
                              {% if item.url %}
                          <a href="{{ item.url }}" class="btn btn-primary" target="_blank">Details</a>
                            {% endif %}
                  -->
            </div>
        </div>
        {% endfor %}
        </div>
        </div>
    </section>
    <hr class="m-0" />

    </div>
    <!-- Bootstrap core JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Third party plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
</body>

</html>

blog/templates/blog/blog_detail.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Resume</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
            <a class="navbar-brand js-scroll-trigger" href="#page-top">
                <span class="d-block d-lg-none">Ajit Singh Kushwaha</span>
                <span class="d-none d-lg-block"><img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{% static 'assets/img/profile_pic2.jpg' %}" alt="" /></span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'index' %}">Home</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'blog:all_blogs' %}">Back</a></li>

                </ul>
            </div>
        </nav>
            <!-- Blog -->
            <section class="resume-section" id="projects">
                <div class="resume-section-content">
                    <!--Blog detail page -->
                    <div class="card mb-3">
                        {% if blog.image %}
                        <img class="card-img-top" src="{{ blog.image.url }}" alt="blog image cap">
                        {% endif %}
                        <div class="card-body">
                          <h4 class="card-title">{{ blog.title }}</h4>
                          <p class="card-text">{{blog.description}}</p>
                          <p class="card-text"><small class="text-muted">{{blog.date}}</small></p>
                        </div>
                      </div>

                </div>
            </section>
            <hr class="m-0" />
            
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

project/templates/project/detail.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Resume</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
            <a class="navbar-brand js-scroll-trigger" href="#page-top">
                <span class="d-block d-lg-none">Ajit Singh Kushwaha</span>
                <span class="d-none d-lg-block"><img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{% static 'assets/img/profile_pic2.jpg' %}" alt="" /></span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'index' %}">Home</a></li>

                </ul>
            </div>
        </nav>
            <!-- Projects -->
            <section class="resume-section" id="projects">
                <div class="resume-section-content">
                   
                    <div class="card mb-3" >
                        <div class="text-center">
                        <img class="card-img-top" style="width: 35rem;" src="{{ project.image.url }}" alt="Card image cap">
                    </div>
                        <div class="card-body">
                          <h4 class="card-title">{{ project.title }}</h4>
                          <p class="card-text">{{ project.description }}</p>
                          {% if project.url %}
                          <a href="{{ project.url }}" class="btn btn-primary" target="_blank">Source</a>
                            {% endif %}
                        </div>
                      </div>
                </div>
            </section>
            <hr class="m-0" />
            
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

project/templates/project/index.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Resume</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />
        <!-- Devicon.dev icons-->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.10.1/devicon.min.css">

        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
            <a class="navbar-brand js-scroll-trigger" href="#page-top">
                <span class="d-block d-lg-none">Ajit Singh Kushwaha</span>
                <span class="d-none d-lg-block"><img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{% static 'assets/img/profile_pic2.jpg' %}" alt="" /></span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#about">About</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#experience">Experience</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#skills">Skills</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#interests">Interests</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#projects">Projects</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'blog:all_blogs' %}">Blog</a></li>
                </ul>
            </div>
        </nav>
        <!-- Page Content-->
        <div class="container-fluid p-0">
            <!-- About-->
            <section class="resume-section" id="about">
                <div class="resume-section-content">
                    <h1 class="mb-0">
                        Ajit Singh
                        <span class="text-primary">Kushwaha</span>
                    </h1>
                    <div class="subheading mb-5">
                        75/76 Chanchal Park · Delhi 110041 · (+91) 8800521646 ·
                        <a href="mailto:ajeetsingh1646@email.com">ajeetsingh1646@email.com</a>
                    </div>
                    <p class="lead mb-5">I am a programmer, machine learning engineer and experienced back-end developer on Dajngo framework. Implementing iterative approaches to enhance, maintain performance of projects and to corporate strategy foster collaborative thinking to further gain in the overall value proposition.
                        <br>
                    Thorough and meticulous Machine Learning Engineer passionate about helping businesses succeed by analysing and creating predictive models on data collected and provided. Possessing strong technical skills rooted in substantial training as an engineer.</p>

                    <div class="social-icons">
                        <a class="social-icon" href="https://www.linkedin.com/in/ajeet-singh-kushwaha-aa399a92"><i class="fab fa-linkedin-in"></i></a>
                        <a class="social-icon" href="https://github.com/ajeetsingh1646"><i class="fab fa-github"></i></a>
                        <a class="social-icon" href="https://twitter.com/ajeetsingh1646"><i class="fab fa-twitter"></i></a>

                    </div>
                </div>
            </section>

            <hr class="m-0" />
            <!-- Experience-->
            <section class="resume-section" id="experience">
                <div class="resume-section-content">
                    <h2 class="mb-5">Experience</h2>
                    <div class="d-flex flex-column flex-md-row justify-content-between mb-5">
                        <div class="flex-grow-1">
                            <h3 class="mb-0">Machine Learning Engineer</h3>
                            <div class="subheading mb-3">Matchball</div>
                            <p>Key role played on collecting data and research done on various machine learning methods and models implemented in sports to enhance players performance and then these models are implemented on Squash data to check the ball trajectory, shot type and predict a better and improved version for athelete.</p>
                        </div>
                        <div class="flex-shrink-0"><span class="text-primary">June, 2017 - August, 2017</span></div>
                    </div>

                    <div class="d-flex flex-column flex-md-row justify-content-between mb-5">
                        <div class="flex-grow-1">
                            <h3 class="mb-0">Web Developer</h3>
                            <div class="subheading mb-3">Superb IT Solutions </div>
                            <p>Intern as a web developer, working on small projects under the guidance of team coordinator on static as well as a few dynamic projects. Converting costumers requirement into well versed applications or websites with known web development languages and frameworks. Enhancing project handling and team player skills. </p>
                        </div>
                        <div class="flex-shrink-0"><span class="text-primary">December, 2016 - January, 2016</span></div>
                    </div>

                    
                    
                </div>
            </section>
            <hr class="m-0" />
            <hr class="m-0" />
            <!-- Skills-->
            <section class="resume-section" id="skills">
                <div class="resume-section-content">
                    <h2 class="mb-5">Skills</h2>
                    <div class="subheading mb-3">Programming Languages & Tools</div>
                    <ul class="list-inline dev-icons" >
                        <li class="list-inline-item" style="padding: .1em;"><i class="fab fa-python"></i>Python</li>
                        <li class="list-inline-item" style="padding: .1em;"><i class="fab fa-html5"></i>HTML</li>
                        <li class="list-inline-item" style="padding: .1em;"><i class="fab fa-css3-alt"></i>CSS</li>
                        <li class="list-inline-item" style="padding: .1em;"><i class="fas fa-code"></i>OOP</li>
                        <li class="list-inline-item" style="padding: .1em;"><i class="fab fa-r-project"></i>R Lang</li>
                        <li class="list-inline-item" style="padding: .1em;"><i class="fab fa-js"></i>JavaScript</li>
                        <li class="list-inline-item" style="padding: .1em;"><i class="fab fa-bootstrap"></i>Bootstrap</li>
                        <li class="list-inline-item" style="padding: .1em;"><i class="devicon-mysql-plain ">MySQL</i></li>
                        </li>
                        
                    </ul><br>
                    <div class="subheading mb-3">Workflow</div>
                    <ul class="fa-ul mb-0">
                        <li>
                            <span class="fa-li"><i class="fas fa-check"></i></span>
                            Mobile-First, Responsive Development
                        </li>
                        <li>
                            <span class="fa-li"><i class="fas fa-check"></i></span>
                            Data analysing and Handling
                        </li>
                        <li>
                            <span class="fa-li"><i class="fas fa-check"></i></span>
                            Supervised, Unsupervied and Reinforcement learning
                        </li>
                        <li>
                            <span class="fa-li"><i class="fas fa-check"></i></span>
                            Cross-platform Dynamic Applications
                        </li>
                    </ul>
                </div>
            </section>
            <hr class="m-0" />
            <!-- Interests-->
            <section class="resume-section" id="interests">
                <div class="resume-section-content">
                    <h2 class="mb-5">Interests</h2>
                    <p>Apart from being a web developer and machine learning engineer, I enjoy most of my time gardening. I love planting herbs and sherbs of different variety. During the warmer months here in Colorado, I enjoy traveling and visiting new places.</p>
                    <p class="mb-0">When forced indoors, I follow a number of sci-fi and fantasy genre movies and television shows, I spend a large amount of my free time exploring the latest technology advancements in the  web development, Data Science world.</p>
                </div>
            </section>
            <hr class="m-0" />
            <!-- Projects -->
            <section class="resume-section" id="projects">
                <div class="resume-section-content">
                    <h2 class="mb-5">Projects</h2>
                    <div class="row">
                {% for item in projects %}    
                    <div class="card" style="width: 18rem;">
                        <a href="{{ item.get_absolute_url }}"><img class="card-img-top" src="{{ item.image.url }}" alt="Card image cap">
                        <div class="card-body">
                          <h5 class="card-title">{{ item.title }}</h5></a>
                          <p class="card-text">{{ item.description|truncatechars:50 }}</p>
                          <!--
                              {% if item.url %}
                          <a href="{{ item.url }}" class="btn btn-primary" target="_blank">Details</a>
                            {% endif %}
                              -->
                        </div>
                      </div>
                {% endfor %}
                </div>
                </div>
            </section>
            <hr class="m-0" />
            
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>